Revert "hrtimer: Annotate lockless access to timer->state"
This reverts commit 190d14f3ddc66f1cfe7f48e83f91d2e3a8b12372.

../kernel/time/hrtimer.c:871:8: error: use of undeclared identifier 'state'; did you mean 'static'?
        if (!(state & HRTIMER_STATE_ENQUEUED))
              ^~~~~
              static
../kernel/time/hrtimer.c:871:8: error: expected expression

Signed-off-by: mawrick26 <mawrick26@gmail.com>