soc: qcom: Fix strlcpy compilation error with clang
Replace size of source with size of the destination in
strlcpy size argument to fix clang compilation error.

Squashed with these as well:

Author: Vasantha Balla <vballa@codeaurora.org>
Date:   Wed Nov 13 17:04:58 2019 +0530

    msm: vidc_3x: Fix clang compilation warnings

    Code changes added to fix below clang warnings
    Wpointer-bool-conversion
    Wunneeded-internal-declaration.

    Change-Id: I3f0c9c88806faaae86ce55114fbfc4a84e47075a
    Signed-off-by: Vasantha Balla <vballa@codeaurora.org>

Author: Naitik Bharadiya <bharad@codeaurora.org>
Date:   Mon Oct 14 16:07:42 2019 +0530

    soc: qcom: msm_bus: Fix compilation error with clang

    Remove self assigned variable to fix -Wself-assign warning
    with clang.

    Change-Id: Ia47d8a3f7a6e926d3186fc618827dda09d81f31f
    Signed-off-by: Naitik Bharadiya <bharad@codeaurora.org>

Author: Naitik Bharadiya <bharad@codeaurora.org>
Date:   Mon Oct 14 16:05:02 2019 +0530

    soc: qcom: glink_debugfs: Fix compilation error with clang

    use destination string size in strlcpy size argument to fix
    clang compilation error.

    Change-Id: Ice7fa2753d07e07c5c214ffb0792450985378643
    Signed-off-by: Naitik Bharadiya <bharad@codeaurora.org>

Author: Stefan Agner <stefan@agner.ch>
Date:   Mon Aug 7 10:31:20 2017 -0700

    lib/mpi: fix build with clang

    Use just @ to denote comments which works with gcc and clang.
    Otherwise clang reports an escape sequence error:
      error: invalid % escape in inline assembly string

    Use %0-%3 as operand references, this avoids:
      error: invalid operand in inline asm: 'umull ${1:r}, ${0:r}, ${2:r}, ${3:r}'

    Also remove superfluous casts on output operands to avoid warnings
    such as:
      warning: invalid use of a cast in an inline asm context requiring an l-value

    Change-Id: I8bcb1361869f1aaf6243476a8cb1075012300e19
    Signed-off-by: Stefan Agner <stefan@agner.ch>
    Acked-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>
    Git-commit: dea632cadd129d1901efde6b1167a6250b2157fb
    Git-repo: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
    Signed-off-by: Gaurav Kohli <gkohli@codeaurora.org>

Author: Preeti Nagar <pnagar@codeaurora.org>
Date:   Mon Mar 18 10:25:15 2019 +0530

    ARM: Fix RTIC MPGen failure with clang compiler

    Add flags for the compilation of RTIC MP. Additional
    checks to ensure rtic mp failure does not cause
    kernel compilation to fail.

    Change-Id: I01c87f848c24b31092b8871f6188ace4a4803ec9
    Signed-off-by: Preeti Nagar <pnagar@codeaurora.org>

Author: Trishansh Bhardwaj <tbhardwa@codeaurora.org>
Date:   Wed Mar 13 14:32:38 2019 +0530

    msm: camera: Fix compilation error with clang

    Fix compilation errors in smmu, flash, ife and cdm.

    Change-Id: If9c80f74c5b0b2c69ea8506d7f0b256f91c80bc0
    Signed-off-by: Trishansh Bhardwaj <tbhardwa@codeaurora.org>

Author: Sankeerth Billakanti <sbillaka@codeaurora.org>
Date:   Wed Mar 6 13:59:22 2019 +0530

    drm/msm/dp: fix clang compilation in dp driver

    Make changes to ensure the DP driver is compiled
    successfully with clang enabled.

    Change-Id: I28d3d5db197beea454460441e853eef143dac0b4
    Signed-off-by: Sankeerth Billakanti <sbillaka@codeaurora.org>

Author: Priyanka Gujjula <pgujjula@codeaurora.org>
Date:   Thu Mar 7 20:03:15 2019 +0530

    msm: vidc: Resolve clang compilation error

    pkt->rg_buffer_info will always evaluate to 'true',
    hence refining the code.

    Change-Id: Ifb686c991b9ae06d449a5a1ec3485823ca9b926c
    Signed-off-by: Priyanka Gujjula <pgujjula@codeaurora.org>

Change-Id: Ia05e562b1524995b1aa98d934bcfa4d2c5642b70
Signed-off-by: Naitik Bharadiya <bharad@codeaurora.org>
Signed-off-by: mydongistiny <jaysonedson@gmail.com>